apiVersion: v1
kind: ReplicationController
metadata:
  name: job0
spec:
  replicas: 1
  selector:
    app: master-service
  template:
    metadata:
      name: imagenet-trainer
      labels:
        app: master-service
    spec:
      containers:
      - name: imagenet-trainer
        image: gcr.io/sonic-column-220616/dloncloud:v11 # TODO Put location of your image on cloud repository
        ports:
        - containerPort: 4545
        - containerPort: 6988
        command: ["python"]
        args:
        - "train.py"
        - "--expid"
        - "v100-zmq"
        - "--model"
        - "resnet50"
        - "--iter"
        - "500"
        - "--devices"
        - "1" # TODO Set the number of GPUs required by your Job
        - "--batch-size"
        - "128"
        - "--profile-freq"
        - "0.5"
        - "--world-size"
        - "2"
        - "--rank"
        - "0"
        - "--use-remote"
        resources:
          limits:
            nvidia.com/gpu: 1 # TODO Set this number to same as the number of GPUs required by your Job
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-k80
        ntype: master
      restartPolicy: Always
